---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: httpd-ex-repo
spec:
  type: git
  params:
  - name: url
    value: https://github.com/Spider-Art/cicd.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: httpd-ex-dev-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/test-cicd/httpd-ex-dev:latest
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: httpd-ex-test-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/test-cicd/httpd-ex-test:latest
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: httpd-ex-prod-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/test-cicd/httpd-ex-prod:latest
